### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by bbakiu** [DKiori/DataMaxExercise#1]
Pershendetje,

te lutem me dergo me email te dhenat e tua te kontaktit.
Nuk arrita te bej lidhjen me databazen tone.

**Comment by DKiori** [comment]
Mirmbrema Z. Bujar,

Keto jane kontaktet e mija:
Full Name: Dalip Qorri
Address: Rr. Kormanet, Lagjia 15, Durres.
Phone Number: +355676745692.
Email: ***@***.***
Neqoftese keni ndonje pyetje, mund te me kontaktoni ne cdo moment.

Best regards,

Dalip Qorri.

**Comment by bbakiu** [comment]
Faleminderit
